name = "cro-partner-web-pixel"
type = "web_pixel_extension"
uid = "eafc99d4-ac0b-ef71-7616-db3748573d857c17e3c5"

runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = false
preferences = false
sale_of_data = "disabled"

[settings]
type = "object"

[settings.fields.sourceID]
name = "Source ID"
description = "Identifies events emitted by the CRO Partner pixel."
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]
